# docker-compose.yml
#version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
    command: sh -c "npm run dev"
    stdin_open: true
    tty: true
