# FROM ubuntu:latest
FROM debian
LABEL authors="phanuel"

ENTRYPOINT ["top", "-b"]

# Dockerfile.dev
#FROM node:18-alpine
FROM node:22-bookworm

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy source code
COPY . .

# Expose development port
EXPOSE 12000

# Start development server
CMD ["npm", "run", "dev"]